### PR TITLE
Converting iDynTree (float) pixels to yarp (unsigned char).

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixed some deprecation warnings.

Related to https://github.com/robotology/idyntree/pull/903

### CODE REVIEW

**Comment by traversaro** [comment]
Can you bump version to 0.0.2 ?

**Comment by traversaro** [comment]
At least until iDynTree 5 is released, we may need to swith to compile iDynTree from source, see https://github.com/robotology/yarp-matlab-bindings/blob/master/.github/workflows/conda-ci.yml for a similar case (in that case YARP is compiled from source).

**Comment by S-Dafarra** [comment]
> At least until iDynTree 5 is released, we may need to swith to compile iDynTree from source, see https://github.com/robotology/yarp-matlab-bindings/blob/master/.github/workflows/conda-ci.yml for a similar case (in that case YARP is compiled from source).

I created the branch ``devel`` with the initial idea of keeping there the code that is related to unreleased versions of ``yarp``/``iDynTree``. On the other hand, I did not consider that the CI would have failed. It would be interesting having the CI automatically picking the development version (``devel`` for ``iDynTree``, ``master`` for ``yarp``) for the code that is in the ``devel`` branch :thinking:

**Comment by traversaro** [comment]
> > At least until iDynTree 5 is released, we may need to swith to compile iDynTree from source, see https://github.com/robotology/yarp-matlab-bindings/blob/master/.github/workflows/conda-ci.yml for a similar case (in that case YARP is compiled from source).
> 
> I created the branch `devel` with the initial idea of keeping there the code that is related to unreleased versions of `yarp`/`iDynTree`. On the other hand, I did not consider that the CI would have failed. It would be interesting having the CI automatically picking the development version (`devel` for `iDynTree`, `master` for `yarp`) for the code that is in the `devel` branch 🤔

You can check the base branch of the PR, but for the time being just switching to compile from source I think it is ok.

**Comment by S-Dafarra** [comment]
> You can check the base branch of the PR, but for the time being just switching to compile from source I think it is ok.

Done in #17.

**Review by traversaro — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Pull request merged**
