### PR TITLE
Bump to 0.0.3

### PR DESCRIPTION
**Pull request by traversaro**
After thinking about it, better release the bug fix before I forget about it.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Ok to me. We just need to understand how to deal with ``devel``, that depends on iDynTree ``devel``

**Comment by traversaro** [comment]
> Ok to me. We just need to understand how to deal with `devel`, that depends on iDynTree `devel`



Ah damn, I forgot about that. Let me forward merge master with devel.

**Comment by traversaro** [comment]
> Ok to me. We just need to understand how to deal with `devel`, that depends on iDynTree `devel`

I merged main in devel. Until we merge devel in main, we can continue to release main with no problems, what do you think?

**Comment by traversaro** [comment]
Ack, I guess your confuson. For some reason we added the breaking change in https://github.com/robotology/idyntree-yarp-tools/commit/d815c9c84907e5d3747dff3bf35b372c6c11ab34 under 0.0.2, even if 0.0.2 was already release under main. I think we can fix that by moving that change under unreleased.

**Comment by S-Dafarra** [comment]
I think what you suggested makes sense. I guess we need to merge ``main`` in ``devel`` also after this PR gets merged then.

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
